output "cluster_id" {
  description = "The id of the EKS cluster."
  value       = module.eks_cluster_fargate.cluster_id
}

output "cluster_arn" {
  description = "The Amazon Resource Name (ARN) of the cluster."
  value       = module.eks_cluster_fargate.cluster_arn
}

output "cluster_certificate_authority_data" {
  description = "Nested attribute containing certificate-authority-data for your cluster. This is the base64 encoded certificate data required to communicate with your cluster."
  value       = module.eks_cluster_fargate.cluster_certificate_authority_data
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks_cluster_fargate.cluster_endpoint
}

output "cluster_version" {
  description = "The Kubernetes server version for the EKS cluster."
  value       = module.eks_cluster_fargate.cluster_version
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks_cluster_fargate.cluster_security_group_id
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks_cluster_fargate.config_map_aws_auth
}

output "cluster_oidc_issuer_url" {
  description = "The URL on the EKS cluster OIDC Issuer"
  value       = module.eks_cluster_fargate.cluster_oidc_issuer_url
}

output "oidc_provider_arn" {
  description = "The ARN of the OIDC Provider if `enable_irsa = true`."
  value       = module.eks_cluster_fargate.oidc_provider_arn
}


output "cloudwatch_log_group_name" {
  description = "Name of cloudwatch log group created"
  value       = module.eks_cluster_fargate.cloudwatch_log_group_name
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks_cluster_fargate.kubeconfig
}

output "kubeconfig_filename" {
  description = "The filename of the generated kubectl config."
  value       = module.eks_cluster_fargate.kubeconfig_filename
}

output "fargate_profile_arns" {
  description = "Outputs from node groups"
  value       = module.eks_cluster_fargate.fargate_profile_arns
}

output "worker_security_group_id" {
  description = "Security group ID attached to the EKS workers."
  value       = module.eks_cluster_fargate.worker_security_group_id
}
