AWSTemplateFormatVersion: "2010-09-09"
Description: "SecretsManager"
Resources:

  SecretDjangoSecretKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: SecretDjangoSecretKey
      Name: SecretDjangoSecretKey
      SecretString: "sample"

  SecretDjangoDatabasePassword:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Description: "SecretDjangoDatabasePassword"
      Name: SecretDjangoDatabasePassword
      SecretString: "sample"
      
Outputs:
  SecretDjangoSecretKeyArn:
    Value: !Ref "SecretDjangoSecretKey"
    Export:
      Name: "SecretDjangoSecretKeyArn"

  SecretDjangoDatabasePasswordArn:
    Value: !Ref "SecretDjangoDatabasePassword"
    Export:
      Name: "SecretDjangoDatabasePasswordArn"
