controller:
  service:
    targetPorts:
      http: http
      https: http
    annotations:
      # ↓AWSのACMにて作成した証明書のARNを貼り付けてください。またマネージメントコンソールにてRoute53にてAレコードをこのクラシックELBを作成する。
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-1:965398552090:certificate/b2e58d8c-be04-4c8e-b0cf-0955e472dc0c

      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
